
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;;
BEGIN;
LOCK TABLES invoices WRITE, invoices_items WRITE, money WRITE, invoices_delivery WRITE;
SELECT MAX(id) FROM invoices WHERE kind = "SALE";
INSERT INTO invoices
  (pk, kind, id, store_id, date1, time1, account_id, qty, total, total_inc_tax, total_cost, total_price, discount1, total_inc_discount1, addition1_type, addition1_per, addition1, addition2_per, addition2, addition3_per, addition3, additions, discount2_per, discount2, discounts, net_cost, net_price, net_total, tax1_per, tax1, tax2_per, tax2, grand_total, customer_pay, customer_change, cashbox1, cashbox1_id, cashbox2, cashbox2_id, cash, cheques, credit, credit_paid, credit_due, payment_type, payment_status, expense1_type, expense1, cashbox_fees, expenses, real_net_cost, profit, cost_errors, reference, store_to_id, salesman_id, reserved, status, shippedby, custom1, custom2, custom3, custom4, custom5, more, due_date, qty_delivered, createdby_id, createdon, editedby_id, editedon)
VALUES
  (NULL, 'SALE', 60976, 1, '2022-03-06', '4:09:55.480', 2, 3, 111.5, 111.5, 0, 111.5, 2, 109.5, '', 0, 10, 0, 0, 0, 0, 10, 0, 5, 7, 0, 114.5, 114.5, 0, 0, 0, 0, 114.5, 0, 0, 0, 1, 0, NULL, 0, 0, 114.5, 0, 114.5, 'CREDIT', 'NOT PAID', '', 0, 0, 0, 0, 114.5, 0, '', NULL, NULL, 0, '', '', '', '', '', '', '', 'ملاحظة', NULL, 3, 1, '2022-03-06 04:10:00.090', NULL, NULL);
  INSERT INTO invoices_items
  (pk, kind, id, store_id, sn, item_id, qty, amount, total, amount_inc_tax, total_inc_tax, unit, uqty1, uqty2, unit_qty_in, unit_qty_out, unit_cost, unit_price, total_cost, total_price, discount1_per, discount1, total_inc_discount1, additions, discount2, discounts, net_cost, net_price, net_total, qty_in, qty_out, cost, price, tax1_per, tax1, tax2_per, tax2, grand_total, expenses, real_net_cost, real_cost, profit, cost_errors, custom1, custom2, custom3, serials, cargo, qty_delivered, unit_contents)
VALUES
  (NULL, 'SALE', 60976, 1, 1, 1, 1, 25, 25, 25, 25, 'كيس', 1, 1, 0, 1, 0, 25, 0, 25, 0, 2, 23, 2.1, 1.05, 3.05, 0, 24.05, 24.05, 0, 1, 0, 24.05, 0, 0, 0, 0, 24.05, 0, 0, 0, 24.05, 0, '', '', '', '', '', 1, 1);
  INSERT INTO invoices_items
  (pk, kind, id, store_id, sn, item_id, qty, amount, total, amount_inc_tax, total_inc_tax, unit, uqty1, uqty2, unit_qty_in, unit_qty_out, unit_cost, unit_price, total_cost, total_price, discount1_per, discount1, total_inc_discount1, additions, discount2, discounts, net_cost, net_price, net_total, qty_in, qty_out, cost, price, tax1_per, tax1, tax2_per, tax2, grand_total, expenses, real_net_cost, real_cost, profit, cost_errors, custom1, custom2, custom3, serials, cargo, qty_delivered, unit_contents)
VALUES
  (NULL, 'SALE', 60976, 1, 2, 10, 1, 76.5, 76.5, 76.5, 76.5, 'كرتونة*6', 6, 1, 0, 1, 0, 76.5, 0, 76.5, 0, 0, 76.5, 6.99, 3.493, 3.493, 0, 79.997, 79.997, 0, 6, 0, 13.3328, 0, 0, 0, 0, 79.997, 0, 0, 0, 79.997, 0, '', '', '', '', '', 1, 6);
  INSERT INTO invoices_items
  (pk, kind, id, store_id, sn, item_id, qty, amount, total, amount_inc_tax, total_inc_tax, unit, uqty1, uqty2, unit_qty_in, unit_qty_out, unit_cost, unit_price, total_cost, total_price, discount1_per, discount1, total_inc_discount1, additions, discount2, discounts, net_cost, net_price, net_total, qty_in, qty_out, cost, price, tax1_per, tax1, tax2_per, tax2, grand_total, expenses, real_net_cost, real_cost, profit, cost_errors, custom1, custom2, custom3, serials, cargo, qty_delivered, unit_contents)
VALUES
  (NULL, 'SALE', 60976, 1, 3, 14, 1, 10, 10, 10, 10, 'كيس', 1, 1, 0, 1, 0, 10, 0, 10, 0, 0, 10, 0.91, 0.457, 0.457, 0, 10.453, 10.453, 0, 1, 0, 10.453, 0, 0, 0, 0, 10.453, 0, 0, 0, 10.453, 0, '', '', '', '', '', 1, 1);
  COMMIT;
  UNLOCK TABLES;
  SET TRANSACTION ISOLATION LEVEL READ COMMITTED;;
  BEGIN;
  SELECT SUM(qty_in) - SUM(qty_out) FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE item_id = 1 AND invoices_items.kind <> "SALEQUOTE"  AND (date1 < "2022-03-06" OR (date1 = "2022-03-06" AND time1 < "04:07:10"));
  SELECT invoices_items.cost, invoices.date1, invoices.time1 FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE item_id = "1" AND (date1 < "2022-03-06" OR (date1 = "2022-03-06" AND time1 < "04:07:10")) AND invoices_items.kind IN ("SALE", "RETURNSALE", "TRANSFER", "INVENT") ORDER BY date1 DESC, time1 DESC LIMIT 1;
  SELECT qty_in, qty_out, real_cost, invoices_items.real_net_cost FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE item_id = "1" AND (date1 > "1999-01-01" OR (date1 = "1999-01-01" AND time1 > "00:00"))                      AND (date1 < "2022-03-06" OR (date1 = "2022-03-06" AND time1 < "04:07:10")) AND invoices_items.kind IN ("OPEN", "PURCHASE", "RETURNPUR", "ADJUST") ORDER BY date1, time1, invoices_items.pk;
  SELECT invoices_items.*, invoices.date1, invoices.time1 FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE item_id = "1" AND (date1 > "2022-03-06" OR (date1 = "2022-03-06" AND time1 >= "04:07:10")) ORDER BY date1, time1, invoices_items.kind, invoices_items.id, invoices_items.sn;
  UPDATE items SET avg_cost = 0,last_net_cost = IFNULL((SELECT invoices_items.real_cost FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE real_cost <> 0 AND invoices_items.item_id = items.id AND  (invoices_items.kind = "PURCHASE" OR invoices_items.kind = "RETURNPUR") ORDER BY invoices.date1 DESC, invoices.time1 DESC LIMIT 1), 0) ,last_cost = IFNULL((SELECT ROUND(unit_cost * uqty2 / uqty1, 4) FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id  WHERE cost <> 0 AND invoices_items.item_id = items.id AND invoices_items.kind IN ("OPEN", "PURCHASE") ORDER BY invoices.date1 DESC, invoices.time1 DESC, invoices_items.store_id DESC LIMIT 1), 0) ,last_purchased = (SELECT date1 FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE invoices_items.item_id = items.id AND invoices_items.kind = "PURCHASE"  ORDER BY invoices.date1 DESC, invoices.time1 DESC LIMIT 1)  WHERE items.id = 1;
  SELECT stores.id, stores_items.qty , (SELECT SUM(qty_in) - SUM(qty_out) FROM invoices_items WHERE invoices_items.store_id = stores.id AND invoices_items.item_id = 1 AND invoices_items.kind <> "SALEQUOTE") AS new_qty , (SELECT service FROM items WHERE id = 1) AS service FROM stores LEFT JOIN stores_items ON stores.id = stores_items.store_id AND stores_items.item_id = 1;
  UPDATE stores_items SET qty = -1 WHERE store_id = 1 AND item_id = 1;
  UPDATE items SET qty = IFNULL((SELECT SUM(qty_in) - SUM(qty_out) FROM invoices_items WHERE invoices_items.item_id = items.id AND invoices_items.kind <> "SALEQUOTE"), 0) WHERE items.id = 1;
  SELECT SUM(qty_in) - SUM(qty_out) FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE item_id = 10 AND invoices_items.kind <> "SALEQUOTE"  AND (date1 < "2022-03-06" OR (date1 = "2022-03-06" AND time1 < "04:07:10"));
  SELECT invoices_items.cost, invoices.date1, invoices.time1 FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE item_id = "10" AND (date1 < "2022-03-06" OR (date1 = "2022-03-06" AND time1 < "04:07:10")) AND invoices_items.kind IN ("SALE", "RETURNSALE", "TRANSFER", "INVENT") ORDER BY date1 DESC, time1 DESC LIMIT 1;
  SELECT qty_in, qty_out, real_cost, invoices_items.real_net_cost FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE item_id = "10" AND (date1 > "1999-01-01" OR (date1 = "1999-01-01" AND time1 > "00:00"))                      AND (date1 < "2022-03-06" OR (date1 = "2022-03-06" AND time1 < "04:07:10")) AND invoices_items.kind IN ("OPEN", "PURCHASE", "RETURNPUR", "ADJUST") ORDER BY date1, time1, invoices_items.pk;
  SELECT invoices_items.*, invoices.date1, invoices.time1 FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE item_id = "10" AND (date1 > "2022-03-06" OR (date1 = "2022-03-06" AND time1 >= "04:07:10")) ORDER BY date1, time1, invoices_items.kind, invoices_items.id, invoices_items.sn;
  UPDATE items SET avg_cost = 0,last_net_cost = IFNULL((SELECT invoices_items.real_cost FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE real_cost <> 0 AND invoices_items.item_id = items.id AND  (invoices_items.kind = "PURCHASE" OR invoices_items.kind = "RETURNPUR") ORDER BY invoices.date1 DESC, invoices.time1 DESC LIMIT 1), 0) ,last_cost = IFNULL((SELECT ROUND(unit_cost * uqty2 / uqty1, 4) FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id  WHERE cost <> 0 AND invoices_items.item_id = items.id AND invoices_items.kind IN ("OPEN", "PURCHASE") ORDER BY invoices.date1 DESC, invoices.time1 DESC, invoices_items.store_id DESC LIMIT 1), 0) ,last_purchased = (SELECT date1 FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE invoices_items.item_id = items.id AND invoices_items.kind = "PURCHASE"  ORDER BY invoices.date1 DESC, invoices.time1 DESC LIMIT 1)  WHERE items.id = 10;
  SELECT stores.id, stores_items.qty , (SELECT SUM(qty_in) - SUM(qty_out) FROM invoices_items WHERE invoices_items.store_id = stores.id AND invoices_items.item_id = 10 AND invoices_items.kind <> "SALEQUOTE") AS new_qty , (SELECT service FROM items WHERE id = 10) AS service FROM stores LEFT JOIN stores_items ON stores.id = stores_items.store_id AND stores_items.item_id = 10;
  UPDATE stores_items SET qty = -6 WHERE store_id = 1 AND item_id = 10;
  UPDATE items SET qty = IFNULL((SELECT SUM(qty_in) - SUM(qty_out) FROM invoices_items WHERE invoices_items.item_id = items.id AND invoices_items.kind <> "SALEQUOTE"), 0) WHERE items.id = 10;
  SELECT SUM(qty_in) - SUM(qty_out) FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE item_id = 14 AND invoices_items.kind <> "SALEQUOTE"  AND (date1 < "2022-03-06" OR (date1 = "2022-03-06" AND time1 < "04:07:10"));
  SELECT invoices_items.cost, invoices.date1, invoices.time1 FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE item_id = "14" AND (date1 < "2022-03-06" OR (date1 = "2022-03-06" AND time1 < "04:07:10")) AND invoices_items.kind IN ("SALE", "RETURNSALE", "TRANSFER", "INVENT") ORDER BY date1 DESC, time1 DESC LIMIT 1;
  SELECT qty_in, qty_out, real_cost, invoices_items.real_net_cost FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE item_id = "14" AND (date1 > "1999-01-01" OR (date1 = "1999-01-01" AND time1 > "00:00"))                      AND (date1 < "2022-03-06" OR (date1 = "2022-03-06" AND time1 < "04:07:10")) AND invoices_items.kind IN ("OPEN", "PURCHASE", "RETURNPUR", "ADJUST") ORDER BY date1, time1, invoices_items.pk;
  SELECT invoices_items.*, invoices.date1, invoices.time1 FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE item_id = "14" AND (date1 > "2022-03-06" OR (date1 = "2022-03-06" AND time1 >= "04:07:10")) ORDER BY date1, time1, invoices_items.kind, invoices_items.id, invoices_items.sn;
  UPDATE items SET avg_cost = 0,last_net_cost = IFNULL((SELECT invoices_items.real_cost FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE real_cost <> 0 AND invoices_items.item_id = items.id AND  (invoices_items.kind = "PURCHASE" OR invoices_items.kind = "RETURNPUR") ORDER BY invoices.date1 DESC, invoices.time1 DESC LIMIT 1), 0) ,last_cost = IFNULL((SELECT ROUND(unit_cost * uqty2 / uqty1, 4) FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id  WHERE cost <> 0 AND invoices_items.item_id = items.id AND invoices_items.kind IN ("OPEN", "PURCHASE") ORDER BY invoices.date1 DESC, invoices.time1 DESC, invoices_items.store_id DESC LIMIT 1), 0) ,last_purchased = (SELECT date1 FROM invoices_items INNER JOIN invoices ON invoices_items.kind = invoices.kind AND invoices_items.id = invoices.id WHERE invoices_items.item_id = items.id AND invoices_items.kind = "PURCHASE"  ORDER BY invoices.date1 DESC, invoices.time1 DESC LIMIT 1)  WHERE items.id = 14;
  SELECT stores.id, stores_items.qty , (SELECT SUM(qty_in) - SUM(qty_out) FROM invoices_items WHERE invoices_items.store_id = stores.id AND invoices_items.item_id = 14 AND invoices_items.kind <> "SALEQUOTE") AS new_qty , (SELECT service FROM items WHERE id = 14) AS service FROM stores LEFT JOIN stores_items ON stores.id = stores_items.store_id AND stores_items.item_id = 14;
  UPDATE stores_items SET qty = -1 WHERE store_id = 1 AND item_id = 14;
  UPDATE items SET qty = IFNULL((SELECT SUM(qty_in) - SUM(qty_out) FROM invoices_items WHERE invoices_items.item_id = items.id AND invoices_items.kind <> "SALEQUOTE"), 0) WHERE items.id = 14;
  COMMIT;


--   if (account_id)
  SELECT accounts.id,  
	IFNULL((SELECT SUM(grand_total) FROM invoices WHERE kind IN ("SALE", "RETURNSALE") AND account_id = 2), 0) -  
	IFNULL((SELECT SUM(grand_total) FROM invoices WHERE kind IN ("PURCHASE", "RETURNPUR") AND account_id = 2), 0) -  
	IFNULL((SELECT SUM(money_in) - SUM(money_out) FROM money WHERE affect_account = 1 AND account_id = 2), 0) AS balance,  
	IFNULL((SELECT SUM(amount) FROM money WHERE (kind = "INSTAL_RECEIPT" OR (kind = "RECEIPT" AND is_cheque = 1)) AND is_liquid = 0 AND is_closed = 0 AND account_id = 2), 0) AS instal_receipts,  
	IFNULL((SELECT SUM(amount) FROM money WHERE (kind = "INSTAL_PAYMENT" OR (kind = "PAYMENT" AND is_cheque = 1)) AND is_liquid = 0 AND is_closed = 0 AND account_id = 2), 0) AS instal_payments,  
	last_sale.date1 AS last_sale_date, last_sale.grand_total AS last_sale_total, last_sale.id AS last_sale_id,  
	last_receipt.date1 AS last_receipt_date, last_receipt.amount AS last_receipt_amount, last_receipt.id AS last_receipt_id  
FROM accounts   
LEFT JOIN (SELECT account_id, id, date1, grand_total FROM invoices WHERE account_id = 2 AND kind = "SALE" ORDER BY date1 DESC, time1 DESC LIMIT 1) last_sale ON last_sale.account_id = accounts.id  
LEFT JOIN (SELECT account_id, id, date1, amount FROM money WHERE account_id = 2 AND kind IN("RECEIPT", "INSTAL_RECEIPT") AND (is_cheque = 1 OR is_liquid = 1) ORDER BY date1 DESC, time1 DESC LIMIT 1) last_receipt ON last_receipt.account_id = accounts.id  
WHERE accounts.id = 2;
UPDATE accounts SET balance_out = 503.5, balance_in = 0, instal_receipts = 0, instal_payments = 0 , last_sale_date = "2022-03-06", last_sale_total = 114.5, last_sale_id = 60976 , last_receipt_date = NULL, last_receipt_amount = 0, last_receipt_id = NULL  WHERE id = 2;



